---
env:
  global:
    - CC_TEST_REPORTER_ID=232fa7b49a89e37b520b8336c4d56fdfac8fc5cbaecef45c780d2484130adcf2

language: node_js
node_js:
  - node


before_script:
  - ./cc-test-reporter before-build

script:
  - make lint
  - nyc --reporter=lcov npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT